python3: Backport patch from upstream to fix test_venv.py issue
The test_venv.py uses shutil but not import it.
Therefore, following error is happened when run ptest.

```
======================================================================
ERROR: test_special_chars_bash (test.test_venv.BasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/test/test_venv.py", line 296, in
test_special_chars_bash
    bash = shutil.which('bash')
NameError: name 'shutil' is not defined
======================================================================
ERROR: test_special_chars_csh (test.test_venv.BasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/test/test_venv.py", line 322, in
test_special_chars_csh
    csh = shutil.which('tcsh') or shutil.which('csh')
NameError: name 'shutil' is not defined
```

To fix this issue, backport patch from upstream[1].

1:
https://github.com/python/cpython/commit/5209e586b7cac9a43b2c44349a26b1b0af06ead3

Signed-off-by: Masami Ichikawa <masami.ichikawa@miraclelinux.com>
(cherry picked from commit 7fa325ab16f486a2d0a688b619b817c5535a27a0)
Signed-off-by: Hirotaka Motai <hirotaka.motai@miraclelinux.com>