python3: Add python3-shell for ptest
The test_special_chars_bash and test_special_chars_csh require shutil
package for its test.

```
======================================================================
ERROR: test_special_chars_bash (test.test_venv.BasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/test/test_venv.py", line 296, in
test_special_chars_bash
    bash = shutil.which('bash')
NameError: name 'shutil' is not defined
======================================================================
ERROR: test_special_chars_csh (test.test_venv.BasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/test/test_venv.py", line 322, in
test_special_chars_csh
    csh = shutil.which('tcsh') or shutil.which('csh')
NameError: name 'shutil' is not defined
```

Signed-off-by: Masami Ichikawa <masami.ichikawa@miraclelinux.com>
(cherry picked from commit d2c429407f7285207db6bbe7cd5b41c8bc5e9264)
Signed-off-by: Hirotaka Motai <hirotaka.motai@miraclelinux.com>