python3: Add patch for pass the test_zipfile test of ptest
Add a patch that fix to following fails of test_zipfile test:

  # python3 -m test -v test_zipfile
  ...
  test test_zipfile crashed -- Traceback (most recent call last):
    File "/usr/lib/python3.7/test/libregrtest/runtest.py", line 166, in runtest_inner
      the_module = importlib.import_module(abstest)
    File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/usr/lib/python3.7/test/test_zipfile.py", line 1210, in <module>
      class OtherTests(unittest.TestCase):
    File "/usr/lib/python3.7/test/test_zipfile.py", line 1683, in OtherTests
      @requires_zlib()
  TypeError: _id() missing 1 required positional argument: 'obj'

  test_zipfile failed
  ...

Signed-off-by: Takahiro Terada <takahiro.terada@miraclelinux.com>